### ISSUE TITLE
Adding problem solving files to R-Instat library

### ISSUE THREAD

**Issue by Kelvin-23** [africanmathsinitiative/R-Instat-Data#3]
After discussing with Roger, there are a few files that are supposed to be added to the next version of R-Instat and then can be read from the File > Open From Library > Instat > Browse. A new directory called Problem Solving is to be made into the R-Instat data library.

I will upload the files so that they can be added as soon as possible.
[AIMS Cameroon paper survey data.xlsx](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467253/AIMS.Cameroon.paper.survey.data.xlsx)
[Islands Data Table1-2.csv](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467254/Islands.Data.Table1-2.csv)
[millet_data.xlsx](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467255/millet_data.xlsx)
[odk_form_aims_cameroon_survey.xls](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467256/odk_form_aims_cameroon_survey.xls)
[rice_survey.csv](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467257/rice_survey.csv)
[SPS Course evaluation_18-19.xlsx](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467258/SPS.Course.evaluation_18-19.xlsx)
[Statistical.Problem.Solving.Survey.csv](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467259/Statistical.Problem.Solving.Survey.csv)
[tomato.csv](https://github.com/africanmathsinitiative/R-Instat-Data/files/7467260/tomato.csv)

**Comment by dannyparsons** [comment]
@Kelvin-23 thanks for this. Can you do a Pull Request with these additions?

I would also prefer a more descriptive name for the folder, maybe "Teaching" or "Problem Solving Examples"

I'm not sure also, if the ODK form should be in the library, as this isn't something I would expect to be analysed in R-Instat?
